/**
 * Prism.js language definition for .orb files.
 *
 * Registry-driven: reads tokens.json (generated from @almadar/operators
 * and @almadar/patterns) to classify tokens. Unknown operators and
 * unregistered patterns get error/warning colors.
 *
 * @packageDocumentation
 */

// tokens.json is generated by scripts/generate-tokens.ts and committed to src/
import tokens from './tokens.json' with { type: 'json' };

// Build regex patterns from token lists

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function wordsToPattern(words: string[]): string {
  // Sort longest first so longer matches take priority
  const sorted = [...words].sort((a, b) => b.length - a.length);
  return sorted.map(escapeRegex).join('|');
}

// All known operators (for detecting unknown ones)
const allOpsSet = new Set(tokens.allOperatorNames);
const patternsSet = new Set(tokens.patternNames);

// Build namespace-specific patterns
const namespacePatterns: Record<string, RegExp> = {};
for (const [ns, ops] of Object.entries(tokens.operatorsByNamespace)) {
  if ((ops as string[]).length > 0) {
    namespacePatterns[ns] = new RegExp(`^"(${wordsToPattern(ops as string[])})"$`);
  }
}

const effectPattern = new RegExp(`^"(${wordsToPattern(tokens.effectTypes)})"$`);
const structuralPattern = new RegExp(`^"(${wordsToPattern(tokens.structuralKeys)})"$`);
const fieldTypePattern = new RegExp(`^"(${wordsToPattern(tokens.fieldTypes)})"$`);
const persistencePattern = new RegExp(`^"(${wordsToPattern(tokens.persistenceKinds)})"$`);
const slotPattern = new RegExp(`^"(${wordsToPattern(tokens.uiSlots)})"$`);
const patternNamesPattern = tokens.patternNames.length > 0
  ? new RegExp(`^"(${wordsToPattern(tokens.patternNames)})"$`)
  : null;
const behaviorPattern = tokens.behaviorNames.length > 0
  ? new RegExp(`^"(${wordsToPattern(tokens.behaviorNames)})"$`)
  : null;

/**
 * Register the 'orb' language with Prism.
 *
 * Call this before any code blocks render:
 *   import { registerOrbLanguage } from '@almadar/syntax';
 *   registerOrbLanguage(Prism);
 */
export function registerOrbLanguage(Prism: Record<string, unknown>): void {
  const languages = Prism.languages as Record<string, unknown>;

  // Extend JSON as the base grammar
  const json = languages.json as Record<string, unknown>;
  if (!json) {
    console.warn('[almadar-syntax] Prism JSON language not found. Load it first.');
    return;
  }

  // Build inside grammar for semantic string classification.
  // Refractor-compatible: uses standard Prism `inside` tokenization,
  // no hooks. Order matters (first match wins).
  const orbInside: Record<string, RegExp | { pattern: RegExp }> = {};

  // 1. Bindings: @entity.field, @payload.x, @Entity.field
  orbInside['orb-binding'] = /"@(?:entity|payload|state|now|config|computed|trait)(?:\.[a-zA-Z0-9_.]+)?"|"@[A-Z][a-zA-Z0-9]*(?:\.[a-zA-Z0-9_.]+)?"/;

  // 2. Effect types
  if (tokens.effectTypes.length > 0) {
    orbInside['orb-effect'] = new RegExp(`"(?:${wordsToPattern(tokens.effectTypes)})"`);
  }

  // 3. Operator namespaces
  for (const [ns, ops] of Object.entries(tokens.operatorsByNamespace)) {
    if ((ops as string[]).length > 0) {
      orbInside[`orb-op-${ns}`] = new RegExp(`"(?:${wordsToPattern(ops as string[])})"`);
    }
  }

  // 4. Events: UPPER_SNAKE_CASE (3+ chars)
  orbInside['orb-event'] = /"[A-Z][A-Z0-9_]{2,}"/;

  // 5. UI slots
  if (tokens.uiSlots.length > 0) {
    orbInside['orb-slot'] = new RegExp(`"(?:${wordsToPattern(tokens.uiSlots)})"`);
  }

  // 6. Structural keys
  if (tokens.structuralKeys.length > 0) {
    orbInside['orb-structural'] = new RegExp(`"(?:${wordsToPattern(tokens.structuralKeys)})"`);
  }

  // 7. Field types
  if (tokens.fieldTypes.length > 0) {
    orbInside['orb-field-type'] = new RegExp(`"(?:${wordsToPattern(tokens.fieldTypes)})"`);
  }

  // 8. Persistence kinds
  if (tokens.persistenceKinds.length > 0) {
    orbInside['orb-persistence'] = new RegExp(`"(?:${wordsToPattern(tokens.persistenceKinds)})"`);
  }

  // 9. Pattern names
  if (tokens.patternNames.length > 0) {
    orbInside['orb-pattern'] = new RegExp(`"(?:${wordsToPattern(tokens.patternNames)})"`);
  }

  // 10. Behavior names
  if (tokens.behaviorNames.length > 0) {
    orbInside['orb-behavior'] = new RegExp(`"(?:${wordsToPattern(tokens.behaviorNames)})"`);
  }

  // 11. Unknown operators: namespaced identifiers not in registry
  orbInside['orb-unknown-op'] = /"[a-z][a-z0-9_-]*\/[a-z][a-z0-9/_-]*"/;

  // Clone JSON property and string tokens, adding the inside grammar
  const jsonProp = json.property as Record<string, unknown>;
  const jsonStr = json.string as Record<string, unknown>;

  languages.orb = {
    ...json,
    property: {
      ...(typeof jsonProp === 'object' ? jsonProp : { pattern: jsonProp }),
      inside: orbInside,
    },
    string: {
      ...(typeof jsonStr === 'object' ? jsonStr : { pattern: jsonStr }),
      inside: orbInside,
    },
  };
}

/**
 * Get the token classification for a string value.
 * Useful for Monaco and other non-Prism consumers.
 */
export function classifyOrbToken(quotedString: string): string {
  // Reuse the same logic without Prism dependency
  if (/^"@(entity|payload|state|now|config|computed|trait)(\.[a-zA-Z0-9_.]+)?"$/.test(quotedString)) return 'binding';
  if (/^"@[A-Z][a-zA-Z0-9]*(\.[a-zA-Z0-9_.]+)?"$/.test(quotedString)) return 'binding';
  if (effectPattern.test(quotedString)) return 'effect';
  for (const [ns, pattern] of Object.entries(namespacePatterns)) {
    if (pattern.test(quotedString)) return ns;
  }
  if (/^"[A-Z][A-Z0-9_]{2,}"$/.test(quotedString)) return 'event';
  if (slotPattern.test(quotedString)) return 'slot';
  if (structuralPattern.test(quotedString)) return 'structural';
  if (fieldTypePattern.test(quotedString)) return 'fieldType';
  if (persistencePattern.test(quotedString)) return 'persistence';
  if (patternNamesPattern?.test(quotedString)) return 'pattern';
  if (behaviorPattern?.test(quotedString)) return 'behavior';
  return 'string';
}

/**
 * Check if an operator name is registered.
 */
export function isRegisteredOperator(name: string): boolean {
  return allOpsSet.has(name);
}

/**
 * Check if a pattern name is registered.
 */
export function isRegisteredPattern(name: string): boolean {
  return patternsSet.has(name);
}
